DROP TABLE IF EXISTS Conditions CASCADE;
DROP TABLE IF EXISTS Participations CASCADE;
DROP TABLE IF EXISTS Emotions CASCADE;
DROP TABLE IF EXISTS Objects CASCADE;
DROP TABLE IF EXISTS Thoughts CASCADE;
DROP TABLE IF EXISTS Events CASCADE;
DROP TABLE IF EXISTS Places CASCADE;
DROP TABLE IF EXISTS Persons CASCADE;

DROP TYPE IF EXISTS SexType CASCADE;
DROP TYPE IF EXISTS EventType CASCADE;
DROP TYPE IF EXISTS ObjectType CASCADE;
DROP TYPE IF EXISTS ParticipateRole CASCADE;
DROP TYPE IF EXISTS EmotionType CASCADE;